### ISSUE TITLE
Clarification on bondi license

### ISSUE THREAD

**Issue by tmcgilchrist** [Barry-Jay/bondi#10]
Could I get some clarity on what license `bondi` is released under before I do any further work on the compiler?

I can see evidence of at least 3 different licenses in the repo:

 * BSD-3 (https://github.com/Barry-Jay/bondi/blob/master/BSD-LICENCE)
 * GPL (https://github.com/Barry-Jay/bondi/blob/master/LICENSE)
 * Apache 2.0 (https://github.com/Barry-Jay/bondi/blob/master/bondi.opam#L8)

@Barry-Jay @javergar

**Comment by ghuntley** [comment]
For comparison sake:

* The .NET compiler is MIT - https://github.com/dotnet/coreclr/blob/master/LICENSE.TXT
* The GHC compiler is BSD-3 - https://git.haskell.org/ghc.git/blob/HEAD:/LICENSE
* The OCaml compiler is LGPL - https://ocaml.org/docs/license.html
* The RUST compiler is MIT - https://github.com/rust-lang/rust/blob/master/LICENSE-MIT
* The LVVM compiler is APACHE2 - http://releases.llvm.org/2.8/LICENSE.TXT

I recommend changing to MIT or BSD-3. My preferred license is MIT. Can we please change to MIT?

**Comment by tmcgilchrist** [comment]
MIT licence merged.
