### ISSUE TITLE
path to the standard prelude

### ISSUE THREAD

**Issue by Barry-Jay** [Barry-Jay/bondi#2]
I had to manually open the standard library, using a relative path, as in
%open ".opam/4.05.0/lib/packages.dev/bondi/prelude/standard_prelude.bon";;

**Comment by aslakg** [comment]
Good stuff - was not previously able to run this on macos (only linux), but with this new opam build it works fine. Need to rlwrap and do the prelude include, but that can be scripted.

**Comment by Barry-Jay** [comment]
Jose fixed this.
